spring.application.name=APIJuliana

# ===============================
# Configuración del servidor
# ===============================
server.port=8080

# ===============================
# Configuración de la base de datos MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/juliana?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=8841
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JWT
# ===============================
jwt.secret=760762fa1e6fccd05d8e1197daf7b7729cb83323474aab95a271c91926359e36
jwt.expiration=3600

# ===============================
# Email
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juliana.lamimaker@gmail.com
spring.mail.password=ibyc oesx sdhp clco
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true